const axios = require("axios");
const fs = require("fs-extra");
const path = require("path");

module.exports = {
  config: {
    name: "mj",
    version: "2.2",
    author: "Farhan",
    description: "Generate AI images using Midjourney Turbo (reply to image or text prompt).",
    category: "image",
    usage: "/mj [prompt] (reply to an image)\nExample: /mj make it cyberpunk",
    usePrefix: true,
    role: 0
  },

  onStart: async function ({ bot, chatId, args, msg }) {
    const prompt = args.join(" ").trim();
    const reply = msg?.reply_to_message;

    if (!prompt && (!reply || !reply.photo)) {
      return bot.sendMessage(
        chatId,
        "⚠️ Please provide a prompt or reply to a photo with a prompt.\nExample: /mj make it anime"
      );
    }

    const waitMsg = await bot.sendMessage(chatId, `⚡ Generating image for prompt: "${prompt || 'Image'}"... Please wait.`);

    try {
      let imageUrl = null;

      // If user replied to an image, get the file URL
      if (reply?.photo) {
        const photo = reply.photo[reply.photo.length - 1]; // highest quality
        const file = await bot.getFile(photo.file_id);
        imageUrl = `https://api.telegram.org/file/bot${bot.token}/${file.file_path}`;
      }

      // Call AI image generation API
      const apiURL = `https://dev.oculux.xyz/api/mj-proxy-pub?prompt=${encodeURIComponent(prompt)}${imageUrl ? `&image=${encodeURIComponent(imageUrl)}` : ''}`;
      const response = await axios.get(apiURL, { responseType: "arraybuffer" });

      // Save image to temp file
      const tempDir = path.join(__dirname, "temp");
      await fs.ensureDir(tempDir);
      const tempFile = path.join(tempDir, `mj_${Date.now()}.png`);
      await fs.writeFile(tempFile, Buffer.from(response.data));

      // Send generated image
      await bot.sendPhoto(chatId, fs.createReadStream(tempFile), {
        caption: `✅ Generated by Midjourney Turbo${prompt ? ` for prompt: "${prompt}"` : ""}`
      });

      // Clean up
      await fs.unlink(tempFile);
      bot.deleteMessage(chatId, waitMsg.message_id).catch(() => {});
    } catch (err) {
      console.error("MJ CMD Error:", err);
      bot.sendMessage(chatId, "❌ Failed to generate image. Please try again later.");
    }
  }
};
    
